package reflector

const (
	// The REFLECTOR_S_IS_NIL error occurs when the s parameter passed to the Load() function is nil.
	SIsNil string = "REFLECTOR_S_IS_NIL"

	// The REFLECTOR_S_IS_NOT_PTR error occurs when the s parameter passed to the Load() function is
	// not a pointer.
	SIsNotPtr string = "REFLECTOR_S_IS_NOT_PTR"

	// The REFLECTOR_NIL_STRUCT_PTR error occurs when the s parameter passed to the Load() function
	// is a nil pointer. The Load() function requires a valid, initialized struct pointer to populate
	// the environment variables.
	NilStructPtr string = "REFLECTOR_NIL_STRUCT_PTR"

	// The REFLECTOR_INVALID_STRUCT_PTR error occurs when the s parameter passed to the Load() function
	// is a pointer that does not point to a valid struct. The Load() function requires a pointer to a
	// valid, initialized struct in order to correctly populate the environment variables.
	InvalidStructPtr string = "REFLECTOR_INVALID_STRUCT_PTR"

	// The REFLECTOR_INVALID_ENV_DATA error is an internal error that occurs when the data parameter,
	// which is a map[string]string containing all key-value pairs generated by the parser, is found to
	// be nil. This issue typically happens when there is a bug in the loader or parser.
	InvalidEnvData string = "REFLECTOR_INVALID_ENV_DATA"

	// The REFLECTOR_DUPLICATE_KEYS error is an internal error that occurs when the data parameter, a
	// map[string]string containing all key-value pairs generated by the parser, contains conflicting keys.
	// This issue typically arises when the parser fails to correctly block duplicate keys due to a bug
	// or unexpected behavior.
	DuplicateKeys string = "REFLECTOR_DUPLICATE_KEYS"

	// The REFLECTOR_MISSING_FIELD error occurs when the struct intended to be populated is missing a field
	// that corresponds to a key-value pair in the .env file.
	MissingField string = "REFLECTOR_MISSING_FIELD"

	// The REFLECTOR_UNSUPPORTED_FIELD error occurs when the struct intended to be populated has a field of
	// a type that is not supported by the reflector for mapping key-value pairs from the .env file.
	//
	// The reflector only supports native Go types, including:
	//
	//	- Numeric types: int (8, 16, 32, 64), uint (8, 16, 32, 64), float (32, 64), complex (64, 128)
	//	- String type: string
	//	- Boolean type: bool
	//	- Time type: time.Time
	UnsupportedType string = "REFLECTOR_UNSUPPORTED_TYPE"

	// The REFLECTOR_UNSETTABLE_FIELD error is an internal error that occurs when the reflector (due to a bug)
	// incorrectly allows either a pointer that does not properly reference a struct or attempts to set unexported
	// (private) fields in the provided struct pointer.
	UnsettableField string = "REFLECTOR_UNSETTABLE_FIELD"

	// The REFLECTOR_UNEXPORTED_FIELD error occurs when the struct intended to be populated contains unexported
	// fields.
	UnexportedField string = "REFLECTOR_UNEXPORTED_FIELD"

	// The REFLECTOR_INVALID_INT error occurs when the value from the .env file intended to populate an int
	// (8, 16, 32, 64) field in the struct is not a valid integer string literal.
	InvalidInt string = "REFLECTOR_INVALID_INT"

	// The REFLECTOR_INVALID_UINT error occurs when the value from the .env file intended to populate a uint
	// (8, 16, 32, 64) field in the struct is not a valid unsigned integer string literal.
	InvalidUint string = "REFLECTOR_INVALID_UINT"

	// The REFLECTOR_INVALID_FLOAT error occurs when the value from the .env file intended to populate a
	// float32 or float64 field in the struct is not a valid float string literal.
	InvalidFloat string = "REFLECTOR_INVALID_FLOAT"

	// The REFLECTOR_INVALID_COMPLEX error occurs when the value from the .env file intended to populate a
	// complex64 or complex128 field in the struct is not a valid complex number string literal.
	InvalidComplex string = "REFLECTOR_INVALID_COMPLEX"

	// The REFLECTOR_INVALID_BOOL error occurs when the value from the .env file intended to populate a bool
	// field in the struct is not a valid boolean string literal.
	InvalidBool string = "REFLECTOR_INVALID_BOOL"

	// The REFLECTOR_INVALID_TIME error occurs when the value from the .env file intended to populate a
	// time.Time field in the struct is not a valid RFC3339Nano string literal.
	InvalidTime string = "REFLECTOR_INVALID_TIME"
)
